-- MySQL Script generated by MySQL Workbench
-- Tue Sep 19 23:46:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aunimal_hotel_pet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aunimal_hotel_pet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aunimal_hotel_pet` DEFAULT CHARACTER SET utf8mb4 ;
USE `aunimal_hotel_pet` ;

-- -----------------------------------------------------
-- Table `aunimal_hotel_pet`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aunimal_hotel_pet`.`pessoa` (
  `id_pessoa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `nascimento` DATE NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `rg` CHAR(11) NOT NULL,
  `sexo` ENUM('M', 'F', 'NI') NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `est_civil` ENUM('SOLTEIRO', 'CASADO', 'DIVORCIADO', 'SEPARADO', 'VIUVO') NOT NULL,
  `nacionalidade` VARCHAR(100) NOT NULL DEFAULT 'Brasil',
  `data_criacao` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_pessoa`),
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `rg` (`rg` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aunimal_hotel_pet`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aunimal_hotel_pet`.`cliente` (
  `id_cliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_criacao` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_pessoa1_idx` (`id_cliente` ASC) INVISIBLE,
  CONSTRAINT `fk_cliente_pessoa1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `aunimal_hotel_pet`.`pessoa` (`id_pessoa`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aunimal_hotel_pet`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aunimal_hotel_pet`.`funcionario` (
  `id_funcionario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_criacao` TIMESTAMP NOT NULL,
  `profissao` VARCHAR(100) NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  INDEX `fk_funcionario_pessoa1_idx` (`id_funcionario` ASC) INVISIBLE,
  CONSTRAINT `fk_funcionario_pessoa1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `aunimal_hotel_pet`.`pessoa` (`id_pessoa`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aunimal_hotel_pet`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aunimal_hotel_pet`.`reserva` (
  `id_reserva` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `check_in` DATETIME NOT NULL,
  `checkout` DATETIME NOT NULL,
  `descricao` TINYTEXT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  `id_cliente` INT UNSIGNED NOT NULL,
  `id_funcionario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `fk_cliente_reserva_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_funcionario_reserva_idx` (`id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_reserva`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `aunimal_hotel_pet`.`cliente` (`id_cliente`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_reserva`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `aunimal_hotel_pet`.`funcionario` (`id_funcionario`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aunimal_hotel_pet`.`cobranca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aunimal_hotel_pet`.`cobranca` (
  `id_cobranca` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_cobranca` DATETIME NOT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  `id_reserva` INT UNSIGNED NOT NULL,
  `id_funcionario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_cobranca`),
  INDEX `fk_cobranca_reserva_idx1` (`id_reserva` ASC) VISIBLE,
  INDEX `fk_cobranca_funcionario_idx` (`id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_cobranca_reserva`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `aunimal_hotel_pet`.`reserva` (`id_reserva`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cobranca_funcionario`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `aunimal_hotel_pet`.`funcionario` (`id_funcionario`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aunimal_hotel_pet`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aunimal_hotel_pet`.`contato` (
  `codigo_pais` TINYINT(3) UNSIGNED ZEROFILL NOT NULL,
  `codigo_area` TINYINT NOT NULL,
  `numero` BIGINT NOT NULL,
  `id_cliente` INT UNSIGNED NOT NULL,
  INDEX `fk_contato_pessoa_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_contato_pessoa`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `aunimal_hotel_pet`.`pessoa` (`id_pessoa`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aunimal_hotel_pet`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aunimal_hotel_pet`.`endereco` (
  `id_endereco` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_criacao` DATETIME NOT NULL,
  `cep` CHAR(8) NOT NULL,
  `logradouro` VARCHAR(50) NOT NULL,
  `numero` SMALLINT UNSIGNED NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(100) NOT NULL,
  `pessoa_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_endereco`, `pessoa_id`),
  INDEX `fk_endereco_pessoa1_idx` (`pessoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `aunimal_hotel_pet`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aunimal_hotel_pet`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aunimal_hotel_pet`.`pagamento` (
  `valor` DECIMAL(10,2) NOT NULL,
  `data_pagamento` DATETIME NOT NULL,
  `mes_referencia` DATE NOT NULL,
  `id_funcionario` INT UNSIGNED NOT NULL,
  INDEX `fk_pagamento_funcionario_idx` (`id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_funcionario`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `aunimal_hotel_pet`.`funcionario` (`id_funcionario`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aunimal_hotel_pet`.`raca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aunimal_hotel_pet`.`raca` (
  `id_raca` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `classificacao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_raca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aunimal_hotel_pet`.`especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aunimal_hotel_pet`.`especie` (
  `id_especie` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('GATO', 'CACHORRO') NOT NULL,
  `id_raca` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_especie`),
  INDEX `fk_especie_raca_idx` (`id_raca` ASC) VISIBLE,
  CONSTRAINT `fk_especie_raca`
    FOREIGN KEY (`id_raca`)
    REFERENCES `aunimal_hotel_pet`.`raca` (`id_raca`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aunimal_hotel_pet`.`pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aunimal_hotel_pet`.`pet` (
  `id_pet` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_criacao` TIMESTAMP NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `peso` DECIMAL(5,2) NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL,
  `pelagem` VARCHAR(100) NOT NULL,
  `porte` ENUM('PP', 'P', 'M', 'G', 'GG') NOT NULL,
  `nascimento` DATE NOT NULL,
  `descricao` TINYTEXT NULL DEFAULT NULL,
  `id_especie` INT UNSIGNED NOT NULL,
  `cliente_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_pet`, `id_especie`),
  INDEX `fk_pet_especie_idx` (`id_especie` ASC) VISIBLE,
  INDEX `fk_pet_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_pet_especie`
    FOREIGN KEY (`id_especie`)
    REFERENCES `aunimal_hotel_pet`.`especie` (`id_especie`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pet_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `aunimal_hotel_pet`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aunimal_hotel_pet`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aunimal_hotel_pet`.`servico` (
  `id_servico` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `valor_total` DECIMAL(10,2) NOT NULL,
  `descricao` TINYTEXT NOT NULL,
  PRIMARY KEY (`id_servico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aunimal_hotel_pet`.`forma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aunimal_hotel_pet`.`forma` (
  `id_forma` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_forma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aunimal_hotel_pet`.`cobranca_forma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aunimal_hotel_pet`.`cobranca_forma` (
  `valor` DECIMAL(10,2) NOT NULL,
  `parcela` VARCHAR(45) NOT NULL,
  `id_cobranca` INT UNSIGNED NOT NULL,
  `id_forma` INT UNSIGNED NOT NULL,
  INDEX `fk_cobranca_forma_cobranca_idx` (`id_cobranca` ASC) VISIBLE,
  INDEX `fk_cobranca_forma_forma_idx` (`id_forma` ASC) VISIBLE,
  CONSTRAINT `fk_cobranca_forma_cobranca`
    FOREIGN KEY (`id_cobranca`)
    REFERENCES `aunimal_hotel_pet`.`cobranca` (`id_cobranca`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cobranca_forma_forma`
    FOREIGN KEY (`id_forma`)
    REFERENCES `aunimal_hotel_pet`.`forma` (`id_forma`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aunimal_hotel_pet`.`pet_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aunimal_hotel_pet`.`pet_servico` (
  `id_pet` INT UNSIGNED NOT NULL,
  `id_servico` INT UNSIGNED NOT NULL,
  INDEX `fk_pet_servico_pet_idx` (`id_pet` ASC) VISIBLE,
  INDEX `fk_pet_servico_servico_idx` (`id_servico` ASC) VISIBLE,
  PRIMARY KEY (`id_pet`, `id_servico`),
  CONSTRAINT `fk_pet_servico_pet`
    FOREIGN KEY (`id_pet`)
    REFERENCES `aunimal_hotel_pet`.`pet` (`id_pet`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pet_servico_servico`
    FOREIGN KEY (`id_servico`)
    REFERENCES `aunimal_hotel_pet`.`servico` (`id_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aunimal_hotel_pet`.`reserva_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aunimal_hotel_pet`.`reserva_servico` (
  `id_reserva` INT UNSIGNED NOT NULL,
  `id_servico` INT UNSIGNED NOT NULL,
  INDEX `fk_reserva_servico_reserva_idx` (`id_reserva` ASC) VISIBLE,
  INDEX `fk_reserva_servico_servico_idx` (`id_servico` ASC) VISIBLE,
  PRIMARY KEY (`id_reserva`, `id_servico`),
  CONSTRAINT `fk_reserva_servico_reserva`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `aunimal_hotel_pet`.`reserva` (`id_reserva`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_servico_servico`
    FOREIGN KEY (`id_servico`)
    REFERENCES `aunimal_hotel_pet`.`servico` (`id_servico`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aunimal_hotel_pet`.`funcionario_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aunimal_hotel_pet`.`funcionario_servico` (
  `id_funcionario` INT UNSIGNED NOT NULL,
  `id_servico` INT UNSIGNED NOT NULL,
  INDEX `fk_funcionario_servico_servico_idx` (`id_servico` ASC) VISIBLE,
  INDEX `fk_funcionario_servico_funcionario_idx` (`id_funcionario` ASC) VISIBLE,
  PRIMARY KEY (`id_funcionario`, `id_servico`),
  CONSTRAINT `fk_funcionario_servico_servico`
    FOREIGN KEY (`id_servico`)
    REFERENCES `aunimal_hotel_pet`.`servico` (`id_servico`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_servico_funcionario`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `aunimal_hotel_pet`.`funcionario` (`id_funcionario`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aunimal_hotel_pet`.`pet_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aunimal_hotel_pet`.`pet_reserva` (
  `id_pet` INT UNSIGNED NOT NULL,
  `id_reserva` INT UNSIGNED NOT NULL,
  INDEX `fk_pet_reserva_reserva_idx` (`id_reserva` ASC) VISIBLE,
  INDEX `fk_pet_reserva_pet_idx` (`id_pet` ASC) VISIBLE,
  PRIMARY KEY (`id_pet`, `id_reserva`),
  CONSTRAINT `fk_pet_reserva_reserva`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `aunimal_hotel_pet`.`reserva` (`id_reserva`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pet_reserva_pet`
    FOREIGN KEY (`id_pet`)
    REFERENCES `aunimal_hotel_pet`.`pet` (`id_pet`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
